# Generated by Django 4.2.10 on 2026-03-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_favorite_color_userprofile_favorite_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
